name: CICD
on: 
  push:
    branches: [capstone]

jobs:
        
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: testing
      uses: actions/setup-node@v2
    - name: Install dependencies
      run: npm ci
    - run: npm test

#   build:
#     needs: test
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
    
#     - name: Build docker image
#       continue-on-error: false

#       run: docker build . --file Dockerfile --tag azmiaang/amongus-todo
  
#     - name: Run Snyk to check for docker image
#       uses: snyk/actions/docker@master
#       env:
#         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#       with:
#         image: azmiaang/amongus-todo
#         args: --severity-threshold=low
        
#   push-docker:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#     - name: Set Up docker Buildx
#       uses: docker/setup-buildx-action@v1
      
#     - name: Login Docker
#       uses: docker/login-action@v1
#       with: 
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
#     - name: Build and push
#       uses: docker/build-push-action@v2
#       with:
#         push: true
#         tags: azmiaang/amongus-todo:latest
        
  ec2-docker-run:
#       needs: whitelist-git-ip
      runs-on: ubuntu-latest
      steps:
      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2
        
      - name: Setting environment variables..
        run: |
          echo "AWS_DEFAULT_REGION=ap-southeast-1" >> $GITHUB_ENV
          echo "AWS_SG_NAME=terraform-20211027050001485200000001" >> $GITHUB_ENV
          
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32    
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
      
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.AWS_USERNAME }}
          host: ${{ secrets.AWS_HOST }}
          script: 
              whoami
#             docker stop amongus-todo
#             docker rm amongus-todo
#             docker pull azmiaang/amongus-todo
#             docker run -d -p 8000:3000 --name=amongus-todo azmiaang/amongus-todo
          key: ${{ secrets.AWS_KEY }}
          
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32    
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        if: always()
   
    
    
    
