name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Update 
      run: apt-get update && apt-get -y upgrade
    
    - name: Build docker image
      continue-on-error: false

      run: docker build . --file Dockerfile --tag azmiaang/amongus-todo
  
    - name: Run Snyk to check for docker image
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: azmiaang/amongus-todo
        args: --severity-threshold:medium
      
    
    
