name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Build docker image
      continue-on-error: false

      run: docker build . --file Dockerfile --tag azmiaang/amongus-todo
  
    - name: Run Snyk to check for docker image
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: azmiaang/amongus-todo
        args: --severity-threshold=low
        
  push-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set Up docker Buildx
      uses: docker/setup-buildx-aciton@v1
      
    - name: Login Docker
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: azmiaang/amongus-todo:latest
   
    
    
    
