name: ci
on: 
  push:
    branches: [capstone]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testing
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Build docker image
      continue-on-error: false

      run: docker build . --file Dockerfile --tag azmiaang/amongus-todo
  
    - name: Run Snyk to check for docker image
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: azmiaang/amongus-todo
        args: --severity-threshold=low
        
  push-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set Up docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login Docker
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: azmiaang/amongus-todo:latest
        
  push-heroku:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "powerx-devtool-hw3"
        heroku_email: "azmi_aang@hotmail.com"
        usedocker: true
   
    
    
    
