name: ssh continuous deployment
on:
  push:
    branches: [capstone]
    
jobs:
  whoami:
    name: whoami
    runs-on: ubuntu-latest
    steps:
    - name: sshcommands
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.AWS_USERNAME }}
        host: ${{ secrets.AWS_HOST }}
        script: whoami
        key: ${{ secrets.AWS_KEY }}
  second:
    name: whoami2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: sshcommands2
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.AWS_USERNAME }}
        host: ${{ secrets.AWS_HOST }}
        script: whoami
        key_path: ./.ssh/id_rsa




